language: objective-c

before_script:

script:

before_deploy:
- rvm use 2.3.0
- gem install fir-cli
- fir --version

deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
